title: "Usama Sadiq Portfolio"
email: usama7274@gmail.com
description: >-
  Personal portfolio built with Jekyll.
baseurl: ""
url: "https://usamasadiq.github.io"

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/
